version: '3.8'

services:
  ec-issuer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - ISSUER_AGENT_BASE_URL=http://mock-ssi-agent:8001
      - PUBLIC_URL=http://localhost:8000
      - DEBUG_METRICS=1
    volumes:
      - ./src:/app/src/
    working_dir: /app

  real-ssi-agent:
    image: cr.surf.nl/edubadges-edubadges/edubadges/ssi-agent:latest
    profiles:
      - real-ssi-agent
    ports:
      - "3033:3033"
    environment:
      UNICORE__PROFILE: development
      UNICORE__APPLICATION_URL: http://localhost:3033
      UNICORE__PUBLIC_URL: http://localhost:8000
      UNICORE__EVENT_STORE__TYPE: in_memory
      UNICORE__SECRET_MANAGER__STRONGHOLD_PASSWORD: very-secret-secure_password
      UNICORE__METRICS__ENABLED: false
      UNICORE__DID_METHODS__DID_JWK__ENABLED: true
      UNICORE__DID_METHODS__DID_JWK__PREFERRED: true
      UNICORE__DID_METHODS__DID_KEY__ENABLED: true
      UNICORE__DID_METHODS__DID_WEB__ENABLED: true

  mock-ssi-agent:
    image: ghcr.io/depado/platypus:latest
    ports:
      - "8001:8001"
    command: --server.port 8001 --server.host 0.0.0.0 --mock mock.yaml
    volumes:
      - ./containers/ssi-agent-mock.yaml:/app/mock.yaml
    working_dir: /app
