version: '3.8'

services:
  ec-issuer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m src.main
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      # Complicated ENV magic, to allow running the ec-issuer with the real-ssi-agent.
      - SSI_AGENT_URL=${SSI_AGENT_URL:-http://mock-ssi-agent:8001}
      - SSI_AGENT_NONCE_ENDPOINT=${SSI_AGENT_NONCE_ENDPOINT:-http://mock-ssi-agent:8001/openid4vci/nonce}
      - SSI_AGENT_CREDENTIAL_ENDPOINT=${SSI_AGENT_CREDENTIAL_ENDPOINT:-http://mock-ssi-agent:8001/openid4vci/credential}
      - PUBLIC_URL=http://localhost:8000
      - POSTGRES_CONNECTION_STRING=postgresql://ecissuer:ecissuer@postgresql:5432/ecissuer
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./src:/app/src/
    working_dir: /app

  real-ssi-agent:
    image: cr.surf.nl/edubadges-educredentials/ssi-agent:latest
    profiles:
      - real-ssi-agent
    ports:
      - "3033:3033"
    environment:
      UNICORE__PROFILE: development
      UNICORE__APPLICATION_URL: http://localhost:3033
      UNICORE__PUBLIC_URL: http://localhost:8000
      UNICORE__EVENT_STORE__TYPE: in_memory
      UNICORE__SECRET_MANAGER__STRONGHOLD_PASSWORD: very-secret-secure_password
      UNICORE__METRICS__ENABLED: false
      UNICORE__DID_METHODS__DID_JWK__ENABLED: true
      UNICORE__DID_METHODS__DID_JWK__PREFERRED: true
      UNICORE__DID_METHODS__DID_KEY__ENABLED: true
      UNICORE__DID_METHODS__DID_WEB__ENABLED: true

  mock-ssi-agent:
    image: ghcr.io/depado/platypus:latest
    ports:
      - "8001:8001"
    command: --server.port 8001 --server.host 0.0.0.0 --mock mock.yaml
    volumes:
      - ./dependencies/platypus/ssi-agent-mock.yaml:/app/mock.yaml
    working_dir: /app

  postgresql:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=ecissuer
      - POSTGRES_PASSWORD=ecissuer
      - POSTGRES_DB=ecissuer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecissuer -d ecissuer"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
