name: Documentation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install latest mdbook and mdbook-mermaid
        run: |
          mdbook_tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          mdbook_url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mermaid_tag=$(curl 'https://api.github.com/repos/badboy/mdbook-mermaid/releases/latest' | jq -r '.tag_name')
          mermaid_url="https://github.com/badboy/mdbook-mermaid/releases/download/${mermaid_tag}/mdbook-mermaid-${mermaid_tag}-x86_64-unknown-linux-musl.tar.gz"
          mkdir mdbook
          curl -sSL $mdbook_url | tar -xz --directory=./mdbook
          curl -sSL $mermaid_url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build Book
        run: |
          cd docs
          mdbook build
      - name: Setup Pages
        # uses: actions/configure-pages@v4
        run: echo "SKIPPED, our educredentials org on github must upgrade to a paid version to allow Github Pages on private repos"
      - name: Upload artifact
        # uses: actions/upload-pages-artifact@v3
        # with:
        #  # Upload entire repository
        #  path: 'docs/book'
        run: echo "SKIPPED, our educredentials org on github must upgrade to a paid version to allow Github Pages on private repos"
      - name: Deploy to GitHub Pages
        id: deployment
        # uses: actions/deploy-pages@v4
        run: echo "SKIPPED, our educredentials org on github must upgrade to a paid version to allow Github Pages on private repos"
